
public class TypeCheck {

    public static double check(PokemonStatus atkPokemon, PokemonStatus defPokemon){

        String atkPokemonType, defPokemonType;

        atkPokemonType = atkPokemon.getType();
        defPokemonType = defPokemon.getType();

        if ((atkPokemonType.equals("노말")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("노말")&&defPokemonType.equals("고스트"))
            ||(atkPokemonType.equals("노말")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("독"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("벌레"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("고스트"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("에스퍼"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("페어리"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("비행"))
            ||(atkPokemonType.equals("비행")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("비행")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("비행")&&defPokemonType.equals("전기"))
            ||(atkPokemonType.equals("독")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("독")&&defPokemonType.equals("독"))
            ||(atkPokemonType.equals("독")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("독")&&defPokemonType.equals("땅"))
            ||(atkPokemonType.equals("독")&&defPokemonType.equals("고스트"))
            ||(atkPokemonType.equals("땅")&&defPokemonType.equals("비행"))
            ||(atkPokemonType.equals("땅")&&defPokemonType.equals("벌레"))
            ||(atkPokemonType.equals("땅")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("바위")&&defPokemonType.equals("땅"))
            ||(atkPokemonType.equals("바위")&&defPokemonType.equals("격투"))
            ||(atkPokemonType.equals("바위")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("독"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("격투"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("비행"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("고스트"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("페어리"))
            ||(atkPokemonType.equals("고스트")&&defPokemonType.equals("악"))
            ||(atkPokemonType.equals("고스트")&&defPokemonType.equals("노말"))
            ||(atkPokemonType.equals("강철")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("강철")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("강철")&&defPokemonType.equals("물"))
            ||(atkPokemonType.equals("강철")&&defPokemonType.equals("전기"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("물"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("드래곤"))
            ||(atkPokemonType.equals("물")&&defPokemonType.equals("물"))
            ||(atkPokemonType.equals("물")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("물")&&defPokemonType.equals("드래곤"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("비행"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("독"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("벌레"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("드래곤"))
            ||(atkPokemonType.equals("전기")&&defPokemonType.equals("땅"))
            ||(atkPokemonType.equals("전기")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("전기")&&defPokemonType.equals("전기"))
            ||(atkPokemonType.equals("전기")&&defPokemonType.equals("드래곤"))
            ||(atkPokemonType.equals("에스퍼")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("에스퍼")&&defPokemonType.equals("에스퍼"))
            ||(atkPokemonType.equals("에스퍼")&&defPokemonType.equals("악"))
            ||(atkPokemonType.equals("얼음")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("얼음")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("얼음")&&defPokemonType.equals("물"))
            ||(atkPokemonType.equals("얼음")&&defPokemonType.equals("얼음"))
            ||(atkPokemonType.equals("드래곤")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("드래곤")&&defPokemonType.equals("페어리"))
            ||(atkPokemonType.equals("악")&&defPokemonType.equals("격투"))
            ||(atkPokemonType.equals("악")&&defPokemonType.equals("악"))
            ||(atkPokemonType.equals("악")&&defPokemonType.equals("페어리"))
            ||(atkPokemonType.equals("페어리")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("페어리")&&defPokemonType.equals("독"))
            ||(atkPokemonType.equals("페어리")&&defPokemonType.equals("강철"))
            ) return 0.8;
        else if(
            (atkPokemonType.equals("격투")&&defPokemonType.equals("노말"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("얼음"))
            ||(atkPokemonType.equals("격투")&&defPokemonType.equals("악"))
            ||(atkPokemonType.equals("비행")&&defPokemonType.equals("격투"))
            ||(atkPokemonType.equals("비행")&&defPokemonType.equals("벌레"))
            ||(atkPokemonType.equals("비행")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("독")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("독")&&defPokemonType.equals("페어리"))
            ||(atkPokemonType.equals("땅")&&defPokemonType.equals("독"))
            ||(atkPokemonType.equals("땅")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("땅")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("땅")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("땅")&&defPokemonType.equals("전기"))
            ||(atkPokemonType.equals("바위")&&defPokemonType.equals("비행"))
            ||(atkPokemonType.equals("바위")&&defPokemonType.equals("벌레"))
            ||(atkPokemonType.equals("바위")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("바위")&&defPokemonType.equals("얼음"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("에스퍼"))
            ||(atkPokemonType.equals("벌레")&&defPokemonType.equals("악"))
            ||(atkPokemonType.equals("고스트")&&defPokemonType.equals("고스트"))
            ||(atkPokemonType.equals("고스트")&&defPokemonType.equals("에스퍼"))
            ||(atkPokemonType.equals("강철")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("강철")&&defPokemonType.equals("얼음"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("벌레"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("강철"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("불꽃")&&defPokemonType.equals("얼음"))
            ||(atkPokemonType.equals("물")&&defPokemonType.equals("땅"))
            ||(atkPokemonType.equals("물")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("물")&&defPokemonType.equals("불꽃"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("땅"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("바위"))
            ||(atkPokemonType.equals("풀")&&defPokemonType.equals("물"))
            ||(atkPokemonType.equals("전기")&&defPokemonType.equals("비행"))
            ||(atkPokemonType.equals("전기")&&defPokemonType.equals("물"))
            ||(atkPokemonType.equals("에스퍼")&&defPokemonType.equals("격투"))
            ||(atkPokemonType.equals("에스퍼")&&defPokemonType.equals("독"))
            ||(atkPokemonType.equals("얼음")&&defPokemonType.equals("비행"))
            ||(atkPokemonType.equals("얼음")&&defPokemonType.equals("땅"))
            ||(atkPokemonType.equals("얼음")&&defPokemonType.equals("풀"))
            ||(atkPokemonType.equals("얼음")&&defPokemonType.equals("드래곤"))
            ||(atkPokemonType.equals("드래곤")&&defPokemonType.equals("드래곤"))
            ||(atkPokemonType.equals("악")&&defPokemonType.equals("고스트"))
            ||(atkPokemonType.equals("악")&&defPokemonType.equals("에스퍼"))
            ||(atkPokemonType.equals("페어리")&&defPokemonType.equals("격투"))
            ||(atkPokemonType.equals("페어리")&&defPokemonType.equals("드래곤"))
            ||(atkPokemonType.equals("페어리")&&defPokemonType.equals("악"))
        ) return 1.25;
        else return 1;
    }
//노말 전기 풀 물 불꽃 페어리 독 바위 벌레
//과제로 나온 포켓몬 고 속성간 효과 참고
}